language: python
python:
- '3.7'
- '3.8'
install: pip install -r requirements.txt
script:
- echo "skipping tests"
deploy:
  provider: pypi
  user: lhgomes
  password:
    secure: TALzvOZkk6NYuo/0dIwdEEaS2SX50KABAjHKCsV6kpqPW3pclDH0/9GzVbikSNCkx0VhIY0HgzUWR4BnN98haiMETi3p/ve+s2BFeyRgtxAdheFQPSsI+FGJB6TNU/xU1vgyhUU2L3fC0WPDoFa19jqE1j7NyUYpXnZHEb6ggZGk+7zuW2ZxV+alAZAm1vtnuh+bJaoM5ieCxHW2e8Wz0EjHMKosQ89xMHpfybx1qq3GyXbNS7TnszJepJCVJqMEVdSiZEKNYRR9axh1FGn1IzCDmvHEGxqVnQ30SJ0HlFjD4QN/ox7A0qAdGE0ZBLHggK/jcU52a77NZY4shc+xIureWX8iWs8oGyFI/tM8FfWiQMR2rv10TXCISXEGPQ7pnvhogBnKyq6nTzr4ZxH5KjBsL7Kru8ldDxwQkdl8b5RmwVJaI2luI09GAb79N7nk8t/IYAZgBKK2rfefnwuzVQXv0KKeZQgMxPZZDWlrF0QNjtzXU/mfuqU9DGCFP8C+tQzth5YdqFPuAjWIgKRBWeMyywpnCtoVgO7avA11965b4AmjZ5oQKn5RLG+tVZoo/Lw6lSGHBjv2r4EEphG+3/cIsj74a0BPAlv4GFQd0HmGKWtTY/4hTE5Fkd6J/bEeuxRB0g4rWsvYMDkoX/5PzY38Pli1YSPsTu/nDdDvrg0=
  on:
    tags: true
    branch: master
